# Generated by Django 4.1.7 on 2023-10-25 00:03

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import shop.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_orders_options_remove_orders_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='ordering_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='my_order',
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(default=shop.models.default_date, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='orders',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='orders',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True, primary_key=True, serialize=False, verbose_name='Номер заказа'),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.BigIntegerField(default=shop.models.default_id, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='shop.product', verbose_name='Товары'),
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BigIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость, руб.')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orders', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция в заказе',
                'verbose_name_plural': 'Позиции в заказе',
            },
        ),
    ]
