# Generated by Django 4.1.7 on 2023-10-25 00:09

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Orders = apps.get_model('shop', 'Orders')
    for row in Orders.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
