# Generated by Django 4.1.7 on 2023-10-25 00:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20231025_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True,
                                   verbose_name='Номер заказа'),
        ),
    ]
