# Generated by Django 4.1.7 on 2024-05-18 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0006_alter_product_to_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalProductBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'дополнительный товар',
                'verbose_name_plural': '1 - Дополнительные товары',
                'ordering': ['order'],
            },
        ),
    ]
