# Generated by Django 4.1.7 on 2024-05-19 23:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_to_order'),
        ('calculator_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorDescriptionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('image', models.FileField(max_length=500, upload_to='calculator_page/calculator_description/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '1 - Описание калькулятора',
                'verbose_name_plural': '1 - Описание калькулятора',
            },
        ),
        migrations.AlterModelOptions(
            name='additionalproductblock',
            options={'ordering': ['order'], 'verbose_name': 'дополнительный товар', 'verbose_name_plural': '2 - Дополнительные товары'},
        ),
        migrations.AlterField(
            model_name='additionalproductblock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_product', to='shop.product', verbose_name='Товар'),
        ),
    ]
