# Generated by Django 4.1.7 on 2023-05-17 19:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_alter_news_created_alter_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 19, 35, 59, 946397, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('reviews', models.TextField(verbose_name='Отзыв')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 5, 17, 19, 35, 59, 947001, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
