# Generated by Django 4.1.7 on 2023-07-13 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_created_alter_reviews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 16, 29, 33, 618343, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 16, 29, 33, 619078, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
