# Generated by Django 4.1.7 on 2023-08-02 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_created_alter_reviews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 7, 38, 40, 156582, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 7, 38, 40, 157301, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
