# Generated by Django 4.1.7 on 2023-10-20 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_reviews_options_alter_news_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 14, 46, 31, 174147, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 14, 46, 31, 174147, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
