# Generated by Django 4.1.7 on 2023-10-24 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_news_created_alter_reviews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 22, 24, 3, 544757, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 22, 24, 3, 546302, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
