# Generated by Django 4.1.7 on 2023-10-25 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_news_created_alter_reviews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 0, 3, 4, 270440, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 0, 3, 4, 270440, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
