# Generated by Django 4.1.7 on 2023-10-25 00:22

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_news_created_alter_reviews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=news.models.default_date, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=news.models.default_date, verbose_name='Дата создания'),
        ),
    ]
