# Generated by Django 4.1.7 on 2023-11-17 01:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0017_alter_orders_name_alter_orders_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddQuestionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('image', models.FileField(max_length=500, upload_to='main_page/add_question/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '13 - Блок "Остались вопросы?"',
                'verbose_name_plural': '13 - Блок "Остались вопросы?"',
            },
        ),
        migrations.CreateModel(
            name='AdvantagesBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Заголовок')),
                ('subtitle_first', ckeditor.fields.RichTextField(verbose_name='Подзаголовок')),
                ('text_first', models.CharField(max_length=500, verbose_name='Описание')),
                ('additional_first', models.CharField(blank=True, max_length=500, null=True, verbose_name='Дополнительный текст')),
                ('subtitle_second', ckeditor.fields.RichTextField(verbose_name='Подзаголовок')),
                ('text_second', models.CharField(max_length=500, verbose_name='Описание')),
                ('additional_second', models.CharField(blank=True, max_length=500, null=True, verbose_name='Дополнительный текст')),
                ('subtitle_third', ckeditor.fields.RichTextField(verbose_name='Подзаголовок')),
                ('text_third', models.CharField(max_length=500, verbose_name='Описание')),
                ('additional_third', models.CharField(blank=True, max_length=500, null=True, verbose_name='Дополнительный текст')),
                ('subtitle_fourth', ckeditor.fields.RichTextField(verbose_name='Подзаголовок')),
                ('text_fourth', models.CharField(max_length=500, verbose_name='Описание')),
                ('additional_fourth', models.CharField(blank=True, max_length=500, null=True, verbose_name='Дополнительный текст')),
                ('subtitle_fifth', ckeditor.fields.RichTextField(verbose_name='Подзаголовок')),
                ('text_fifth', models.CharField(max_length=500, verbose_name='Описание')),
                ('additional_fifth', models.CharField(blank=True, max_length=500, null=True, verbose_name='Дополнительный текст')),
                ('subtitle_sixth', ckeditor.fields.RichTextField(verbose_name='Подзаголовок')),
                ('text_sixth', models.CharField(max_length=500, verbose_name='Описание')),
                ('additional_sixth', models.CharField(blank=True, max_length=500, null=True, verbose_name='Дополнительный текст')),
            ],
            options={
                'verbose_name': '8 - Преимущества компании',
                'verbose_name_plural': '8 - Преимущества компании',
            },
        ),
        migrations.CreateModel(
            name='CartonInfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('quality_block', models.CharField(max_length=500, verbose_name='Текст о качестве')),
                ('subtitle_first', models.CharField(max_length=500, verbose_name='Подзаголовок')),
                ('text_first', models.CharField(max_length=500, verbose_name='Описание')),
                ('image_first', models.FileField(max_length=500, upload_to='main_page/carton_info/', verbose_name='Фото')),
                ('subtitle_second', models.CharField(max_length=500, verbose_name='Подзаголовок')),
                ('text_second', models.CharField(max_length=500, verbose_name='Описание')),
                ('image_second', models.FileField(max_length=500, upload_to='main_page/carton_info/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '9 - Информация о картоне',
                'verbose_name_plural': '9 - Информация о картоне',
            },
        ),
        migrations.CreateModel(
            name='CatalogTeaserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': '3 - Тизер каталога',
                'verbose_name_plural': '3 - Тизер каталога',
            },
        ),
        migrations.CreateModel(
            name='ContactsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Заголовок')),
                ('tg_link', models.CharField(max_length=255, verbose_name='ссылка на Telegram')),
                ('whatsapp_link', models.CharField(max_length=255, verbose_name='ссылка на Whatsapp')),
                ('monday_friday_schedule', models.CharField(help_text='чч:мм-чч:мм', max_length=255, verbose_name='Расписание (понедельник-пятница)')),
                ('sunday_schedule', models.CharField(help_text='чч:мм-чч:мм', max_length=255, verbose_name='Расписание (суббота)')),
                ('dinner_schedule', models.CharField(help_text='чч:мм-чч:мм', max_length=255, verbose_name='Расписание (обед)')),
                ('number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('mail', models.CharField(max_length=255, verbose_name='Почта')),
            ],
            options={
                'verbose_name': '12 - Контакты',
                'verbose_name_plural': '12 - Контакты',
            },
        ),
        migrations.CreateModel(
            name='DeliveryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('subtitle_first', models.CharField(max_length=500, verbose_name='Подзаголовок')),
                ('text_first', models.CharField(max_length=500, verbose_name='Описание')),
                ('additional_first', models.CharField(blank=True, max_length=500, null=True, verbose_name='Дополнительный текст')),
                ('image_first', models.FileField(max_length=500, upload_to='main_page/delivery/', verbose_name='Фото')),
                ('subtitle_second', models.CharField(max_length=500, verbose_name='Подзаголовок')),
                ('text_second', models.CharField(max_length=500, verbose_name='Описание')),
                ('additional_second', models.CharField(blank=True, max_length=500, null=True, verbose_name='Дополнительный текст')),
                ('image_second', models.FileField(max_length=500, upload_to='main_page/delivery/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '7 - Доставка',
                'verbose_name_plural': '7 - Доставка',
            },
        ),
        migrations.CreateModel(
            name='HeaderBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(max_length=500, upload_to='main_page/header/', verbose_name='Логотип')),
                ('number', models.CharField(max_length=255, verbose_name='Номер компании')),
                ('mail', models.CharField(help_text='Используется в футере', max_length=255, verbose_name='Почта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес компании')),
                ('tg_link', models.CharField(help_text='Используется в футере', max_length=255, verbose_name='ссылка на Telegram')),
                ('whatsapp_link', models.CharField(help_text='Используется в футере', max_length=255, verbose_name='ссылка на Whatsapp')),
            ],
            options={
                'verbose_name': '1 - Навигационная панель',
                'verbose_name_plural': '1 - Навигационная панель',
            },
        ),
        migrations.CreateModel(
            name='MainBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250, verbose_name='Название компании')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('bar_first', models.CharField(max_length=250, verbose_name='Планка №1')),
                ('bar_second', models.CharField(max_length=250, verbose_name='Планка №2')),
                ('bar_third', models.CharField(max_length=250, verbose_name='Планка №3')),
                ('bar_fourth', models.CharField(max_length=250, verbose_name='Планка №4')),
                ('image', models.FileField(max_length=500, upload_to='main_page/main/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '2 - Главный блок',
                'verbose_name_plural': '2 - Главный блок',
            },
        ),
        migrations.CreateModel(
            name='QuestionsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': '11 - Частые вопросы',
                'verbose_name_plural': '11 - Частые вопросы',
            },
        ),
        migrations.CreateModel(
            name='RequestBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('image', models.FileField(max_length=500, upload_to='main_page/request/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '10 - Блок заявки в Whatsapp',
                'verbose_name_plural': '10 - Блок заявки в Whatsapp',
            },
        ),
        migrations.CreateModel(
            name='ServiceOptionsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('option_first', models.CharField(max_length=50, verbose_name='Текст №1')),
                ('image_first', models.FileField(max_length=500, upload_to='main_page/service_options/', verbose_name='Фото №1')),
                ('option_second', models.CharField(max_length=50, verbose_name='Текст №2')),
                ('image_second', models.FileField(max_length=500, upload_to='main_page/service_options/', verbose_name='Фото №2')),
                ('option_third', models.CharField(max_length=50, verbose_name='Текст №3')),
                ('image_third', models.FileField(max_length=500, upload_to='main_page/service_options/', verbose_name='Фото №3')),
            ],
            options={
                'verbose_name': '4 - Услуги компании',
                'verbose_name_plural': '4 - Услуги компании',
            },
        ),
        migrations.CreateModel(
            name='PopularProductBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'популярная модель',
                'verbose_name_plural': '6 - Популярные модели',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewProductBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'новинка',
                'verbose_name_plural': '5 - Новинки',
                'ordering': ['order'],
            },
        ),
    ]
