# Generated by Django 4.1.7 on 2023-11-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddQuestionBlock',
        ),
        migrations.DeleteModel(
            name='HeaderBlock',
        ),
        migrations.AlterModelOptions(
            name='advantagesblock',
            options={'verbose_name': '7 - Преимущества компании', 'verbose_name_plural': '7 - Преимущества компании'},
        ),
        migrations.AlterModelOptions(
            name='cartoninfoblock',
            options={'verbose_name': '8 - Информация о картоне', 'verbose_name_plural': '8 - Информация о картоне'},
        ),
        migrations.AlterModelOptions(
            name='catalogteaserblock',
            options={'verbose_name': '2 - Тизер каталога', 'verbose_name_plural': '2 - Тизер каталога'},
        ),
        migrations.AlterModelOptions(
            name='contactsblock',
            options={'verbose_name': '11 - Контакты', 'verbose_name_plural': '11 - Контакты'},
        ),
        migrations.AlterModelOptions(
            name='deliveryblock',
            options={'verbose_name': '6 - Доставка', 'verbose_name_plural': '6 - Доставка'},
        ),
        migrations.AlterModelOptions(
            name='mainblock',
            options={'verbose_name': '1 - Главный блок', 'verbose_name_plural': '1 - Главный блок'},
        ),
        migrations.AlterModelOptions(
            name='newproductblock',
            options={'ordering': ['order'], 'verbose_name': 'новинка', 'verbose_name_plural': '4 - Новинки'},
        ),
        migrations.AlterModelOptions(
            name='popularproductblock',
            options={'ordering': ['order'], 'verbose_name': 'популярная модель', 'verbose_name_plural': '5 - Популярные модели'},
        ),
        migrations.AlterModelOptions(
            name='questionsblock',
            options={'ordering': ['order'], 'verbose_name': '10 - Частые вопросы', 'verbose_name_plural': '10 - Частые вопросы'},
        ),
        migrations.AlterModelOptions(
            name='requestblock',
            options={'verbose_name': '9 - Блок заявки в Whatsapp', 'verbose_name_plural': '9 - Блок заявки в Whatsapp'},
        ),
        migrations.AlterModelOptions(
            name='serviceoptionsblock',
            options={'verbose_name': '3 - Услуги компании', 'verbose_name_plural': '3 - Услуги компании'},
        ),
        migrations.AlterField(
            model_name='mainblock',
            name='bar_first',
            field=models.CharField(max_length=250, verbose_name='Карточка №1'),
        ),
        migrations.AlterField(
            model_name='mainblock',
            name='bar_fourth',
            field=models.CharField(max_length=250, verbose_name='Карточка №4'),
        ),
        migrations.AlterField(
            model_name='mainblock',
            name='bar_second',
            field=models.CharField(max_length=250, verbose_name='Карточка №2'),
        ),
        migrations.AlterField(
            model_name='mainblock',
            name='bar_third',
            field=models.CharField(max_length=250, verbose_name='Карточка №3'),
        ),
        migrations.AlterField(
            model_name='serviceoptionsblock',
            name='image_first',
            field=models.FileField(max_length=500, upload_to='main_page/service_options/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='serviceoptionsblock',
            name='image_second',
            field=models.FileField(max_length=500, upload_to='main_page/service_options/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='serviceoptionsblock',
            name='image_third',
            field=models.FileField(max_length=500, upload_to='main_page/service_options/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='serviceoptionsblock',
            name='option_first',
            field=models.CharField(max_length=50, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='serviceoptionsblock',
            name='option_second',
            field=models.CharField(max_length=50, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='serviceoptionsblock',
            name='option_third',
            field=models.CharField(max_length=50, verbose_name='Текст'),
        ),
    ]
