# Generated by Django 4.1.7 on 2024-07-09 22:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantagesblock',
            options={'verbose_name': '8 - Преимущества компании', 'verbose_name_plural': '8 - Преимущества компании'},
        ),
        migrations.CreateModel(
            name='CalculatorBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('image', models.FileField(max_length=500, upload_to='main_page/calculator/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '4 - Блок калькулятора',
                'verbose_name_plural': '4 - Блок калькулятора',
            },
        ),
        migrations.AlterModelOptions(
            name='cartoninfoblock',
            options={'verbose_name': '9 - Информация о картоне', 'verbose_name_plural': '9 - Информация о картоне'},
        ),
        migrations.AlterModelOptions(
            name='contactsblock',
            options={'verbose_name': '12 - Контакты', 'verbose_name_plural': '12 - Контакты'},
        ),
        migrations.AlterModelOptions(
            name='deliveryblock',
            options={'verbose_name': '7 - Доставка', 'verbose_name_plural': '7 - Доставка'},
        ),
        migrations.AlterModelOptions(
            name='newproductblock',
            options={'ordering': ['order'], 'verbose_name': 'новинка', 'verbose_name_plural': '5 - Новинки'},
        ),
        migrations.AlterModelOptions(
            name='popularproductblock',
            options={'ordering': ['order'], 'verbose_name': 'популярная модель', 'verbose_name_plural': '6 - Популярные модели'},
        ),
        migrations.AlterModelOptions(
            name='questionsblock',
            options={'ordering': ['order'], 'verbose_name': '11 - Частые вопросы', 'verbose_name_plural': '11 - Частые вопросы'},
        ),
        migrations.AlterModelOptions(
            name='requestblock',
            options={'verbose_name': '10 - Блок заявки в Whatsapp', 'verbose_name_plural': '10 - Блок заявки в Whatsapp'},
        ),
    ]
