# Generated by Django 4.1.7 on 2023-11-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_delete_addquestionblock_delete_headerblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestblock',
            name='whatsapp_link',
            field=models.CharField(default='', help_text='Используется в кнопке', max_length=255, verbose_name='Ссылка на Whatsapp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactsblock',
            name='tg_link',
            field=models.CharField(max_length=255, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AlterField(
            model_name='contactsblock',
            name='whatsapp_link',
            field=models.CharField(max_length=255, verbose_name='Ссылка на Whatsapp'),
        ),
    ]
