# Generated by Django 4.1.7 on 2023-11-23 21:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_requestblock_whatsapp_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoninfoblock',
            name='image_first',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=None, size=[250, None], upload_to='main_page/carton_info/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='cartoninfoblock',
            name='image_second',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=None, size=[250, None], upload_to='main_page/carton_info/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='deliveryblock',
            name='image_first',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=None, size=[550, None], upload_to='main_page/delivery/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='deliveryblock',
            name='image_second',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=None, size=[550, None], upload_to='main_page/delivery/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='requestblock',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=None, size=[550, None], upload_to='main_page/request/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='serviceoptionsblock',
            name='image_first',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=None, size=[300, None], upload_to='main_page/service_options/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='serviceoptionsblock',
            name='image_second',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=None, size=[300, None], upload_to='main_page/service_options/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='serviceoptionsblock',
            name='image_third',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=None, size=[300, None], upload_to='main_page/service_options/', verbose_name='Фото'),
        ),
    ]
