# Generated by Django 4.1.7 on 2026-02-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_newproductblock_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsblock',
            name='max_link',
            field=models.CharField(default='https://max.ru/u/f9LHodD0cOKZhk6BBd53tajoqsgHshJHe-HnWneXmnVi31D0ym7gdn98dCI', max_length=255, verbose_name='Ссылка на MAX'),
        ),
        migrations.AddField(
            model_name='contactsblock',
            name='vk_link',
            field=models.CharField(default='https://vk.ru/cubekazan', max_length=255, verbose_name='Ссылка на VK'),
        ),
    ]
