# Generated by Django 4.1.7 on 2023-12-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_alter_cartoninfoblock_image_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoninfoblock',
            name='image_first',
            field=models.FileField(max_length=500, upload_to='main_page/carton_info/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='cartoninfoblock',
            name='image_second',
            field=models.FileField(max_length=500, upload_to='main_page/carton_info/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='deliveryblock',
            name='image_first',
            field=models.FileField(max_length=500, upload_to='main_page/delivery/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='deliveryblock',
            name='image_second',
            field=models.FileField(max_length=500, upload_to='main_page/delivery/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='requestblock',
            name='image',
            field=models.FileField(max_length=500, upload_to='main_page/request/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='serviceoptionsblock',
            name='image_first',
            field=models.FileField(max_length=500, upload_to='main_page/service_options/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='serviceoptionsblock',
            name='image_second',
            field=models.FileField(max_length=500, upload_to='main_page/service_options/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='serviceoptionsblock',
            name='image_third',
            field=models.FileField(max_length=500, upload_to='main_page/service_options/', verbose_name='Фото'),
        ),
    ]
