# Generated by Django 4.1.7 on 2023-11-23 21:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsideview',
            name='image_first',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=None, size=[610, None], upload_to='contacts_page/outside_view/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='outsideview',
            name='image_second',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=None, size=[610, None], upload_to='contacts_page/outside_view/', verbose_name='Фото'),
        ),
    ]
