# Generated by Django 4.1.7 on 2023-12-12 23:14

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_page', '0002_alter_outsideview_image_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsideview',
            name='image_third',
            field=django_resized.forms.ResizedImageField(crop=None, default='', force_format=None, keep_meta=True, quality=80, scale=None, size=[610, None], upload_to='contacts_page/outside_view/', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outsideview',
            name='text_third',
            field=models.CharField(default='', max_length=500, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
