# Generated by Django 4.1.7 on 2023-12-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_page', '0003_outsideview_image_third_outsideview_text_third'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsideview',
            name='image_first',
            field=models.FileField(max_length=500, upload_to='contacts_page/outside_view/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='outsideview',
            name='image_second',
            field=models.FileField(max_length=500, upload_to='contacts_page/outside_view/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='outsideview',
            name='image_third',
            field=models.FileField(max_length=500, upload_to='contacts_page/outside_view/', verbose_name='Фото'),
        ),
    ]
