# Generated by Django 4.1.7 on 2024-01-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_1',
            field=models.FloatField(null=True, verbose_name='Цена от 1 шт'),
        ),
    ]
