# Generated by Django 4.1.7 on 2023-10-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_options_category_ordering_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_name_pr_edfda1_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_product',
            new_name='name',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='shop_produc_name_a2070e_idx'),
        ),
    ]
