# Generated by Django 4.1.7 on 2024-02-01 19:05

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_price_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, scale=None, size=[570, 470], upload_to='shop/images', verbose_name='Фотография товара'),
        ),
    ]
