# Generated by Django 4.1.7 on 2023-10-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_shop_produc_name_pr_edfda1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_of_cardboard',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Размеры Товара'),
        ),
    ]
