# Generated by Django 4.1.7 on 2024-05-16 22:38

from django.db import migrations, models

def migrate_in_stock_to_status(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    for product in Product.objects.all():
        if product.in_stock:
            product.status = 'in_stock'
        else:
            product.status = 'out_of_stock'
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='to_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во товаров под заказ'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('out_of_stock', 'Отсутствует'), ('to_order', 'Под заказ')], default='in_stock', max_length=20, verbose_name='Статус товара'),
        ),

        migrations.RunPython(migrate_in_stock_to_status),

        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
    ]
