# Generated by Django 4.1.7 on 2024-05-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_in_stock_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='to_order',
            field=models.IntegerField(blank=True, help_text='Если статус товара "Под заказ" нужно ввести кол-во товаров', null=True, verbose_name='Кол-во товаров под заказ'),
        ),
    ]
