# Generated by Django 4.1.7 on 2023-10-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(default='Чистопольская ул. 7, Казань', max_length=70, verbose_name='Адрес доставки'),
        ),
    ]
