# Generated by Django 4.1.7 on 2023-10-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_orders_options_alter_productlist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Номер телефона'),
        ),
    ]
