# Generated by Django 4.1.7 on 2023-10-25 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_orders_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=70, unique=True, verbose_name='Транслитерация'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='shop/images', verbose_name='Фотография товара (deprecated)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_1',
            field=models.FloatField(verbose_name='Цена от 1 (deprecated)'),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(help_text='От какого кол-ва товара начинает действовать оптовая цена', verbose_name='Кол-во товара')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена за ед. товара при указанном кол-ве товара', max_digits=10, verbose_name='Цена')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'ordering': ['order'],
                'unique_together': {('product', 'count')},
            },
        ),
    ]
