# Generated by Django 4.1.7 on 2023-11-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_category_slug_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('created', 'Заказ создан'), ('material_purchase', 'Закупка сырья'), ('felling', 'Вырубка'), ('packing', 'На упаковке'), ('ready_on_stock', 'Готов на складе'), ('ready_on_shop', 'Готов в магазине'), ('completed', 'Сдан'), ('unknown', 'Неизвестно'), ('return', 'Возврат')], default='created', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='orders',
            name='pickup',
            field=models.BooleanField(default=True, verbose_name='Самовывоз'),
        ),
        migrations.AddField(
            model_name='orders',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ссылка на WhatsApp'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(blank=True, default='', max_length=70, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_1',
            field=models.FloatField(verbose_name='Цена от 1 шт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Размер'),
        ),
    ]
