# Generated by Django 4.1.7 on 2023-11-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_orders_comment_orders_order_status_orders_pickup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='whatsapp_link',
            field=models.URLField(blank=True, max_length=100, verbose_name='Ссылка на WhatsApp'),
        ),
    ]
