# Generated by Django 4.1.7 on 2023-11-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_orders_whatsapp_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(max_length=30, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='Номер телефона'),
        ),
    ]
