# Generated by Django 4.1.7 on 2024-01-08 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_orders_name_alter_orders_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductList',
            new_name='ProductInfo',
        ),
    ]
