# Generated by Django 4.1.7 on 2023-11-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('question_link', models.CharField(max_length=500, verbose_name='Ссылка на чат')),
                ('subtitle_first', models.CharField(max_length=500, verbose_name='Подзаголовок')),
                ('text_first', models.CharField(max_length=500, verbose_name='Описание')),
                ('image_first', models.FileField(max_length=500, upload_to='delivery_page/payment/', verbose_name='Фото')),
                ('subtitle_second', models.CharField(max_length=500, verbose_name='Подзаголовок')),
                ('text_second', models.CharField(max_length=500, verbose_name='Описание')),
                ('image_second', models.FileField(max_length=500, upload_to='delivery_page/payment/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '1 - Доставка',
                'verbose_name_plural': '1 - Доставка',
            },
        ),
    ]
