# Generated by Django 4.1.7 on 2023-11-19 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '1 - Оплата', 'verbose_name_plural': '1 - Оплата'},
        ),
    ]
