# Generated by Django 4.1.7 on 2023-11-19 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_page', '0002_alter_payment_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='PaymentBlock',
        ),
    ]
