# Generated by Django 4.1.7 on 2023-11-23 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_page', '0003_rename_payment_paymentblock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentblock',
            options={'verbose_name': '2 - Оплата', 'verbose_name_plural': '2 - Оплата'},
        ),
    ]
