# Generated by Django 4.1.7 on 2023-12-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_page', '0005_alter_paymentblock_image_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentblock',
            name='image_first',
            field=models.FileField(max_length=500, upload_to='delivery_page/payment/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='paymentblock',
            name='image_second',
            field=models.FileField(max_length=500, upload_to='delivery_page/payment/', verbose_name='Фото'),
        ),
    ]
