# Generated by Django 4.1.7 on 2023-11-18 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0017_alter_orders_name_alter_orders_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddQuestionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('image', models.FileField(max_length=500, upload_to='common_elements/add_question/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Блок "Остались вопросы?"',
                'verbose_name_plural': 'Блок "Остались вопросы?" (Главная, страницы доставки, контактов, о компании, отзывов)',
            },
        ),
        migrations.CreateModel(
            name='HeaderBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(max_length=500, upload_to='common_elements/header/', verbose_name='Логотип')),
                ('number', models.CharField(max_length=255, verbose_name='Номер компании')),
                ('mail', models.CharField(help_text='Используется в футере', max_length=255, verbose_name='Почта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес компании')),
                ('tg_link', models.CharField(help_text='Используется в футере', max_length=255, verbose_name='ссылка на Telegram')),
                ('whatsapp_link', models.CharField(help_text='Используется в футере', max_length=255, verbose_name='ссылка на Whatsapp')),
            ],
            options={
                'verbose_name': 'Навигационная панель и футер',
                'verbose_name_plural': 'Навигационная панель и футер (Все страницы)',
            },
        ),
        migrations.CreateModel(
            name='RecommendedProductBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Рекомендуемые товары',
                'verbose_name_plural': 'Рекомендуемые товары (Страницы товара, доставки, отзывов)',
                'ordering': ['order'],
            },
        ),
    ]
