# Generated by Django 4.1.7 on 2026-02-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_elements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerblock',
            name='max_link',
            field=models.CharField(default='https://max.ru/u/f9LHodD0cOKZhk6BBd53tajoqsgHshJHe-HnWneXmnVi31D0ym7gdn98dCI', help_text='Используется в футере', max_length=255, verbose_name='Ссылка на MAX'),
        ),
        migrations.AddField(
            model_name='headerblock',
            name='vk_link',
            field=models.CharField(default='https://vk.ru/cubekazan', help_text='Используется в футере', max_length=255, verbose_name='Ссылка на VK'),
        ),
    ]
