# Generated by Django 4.1.7 on 2023-11-23 21:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('common_elements', '0003_alter_addquestionblock_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addquestionblock',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=None, size=[1100, None], upload_to='common_elements/add_question/', verbose_name='Фото'),
        ),
    ]
