# Generated by Django 4.1.7 on 2023-12-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_elements', '0005_headerblock_yandex_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addquestionblock',
            name='image',
            field=models.FileField(max_length=500, upload_to='common_elements/add_question/', verbose_name='Фото'),
        ),
    ]
