# Generated by Django 4.1.7 on 2023-11-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddQuestionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('whatsapp_link', models.CharField(help_text='Используется в кнопке', max_length=255, verbose_name='ссылка на Whatsapp')),
                ('image', models.FileField(max_length=500, upload_to='catalog_page/add_question/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '1 - Блок "Не нашли нужный размер?"',
                'verbose_name_plural': '1 - Блок "Не нашли нужный размер?"',
            },
        ),
    ]
