# Generated by Django 4.1.7 on 2023-11-23 21:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_page', '0002_alter_addquestionblock_whatsapp_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addquestionblock',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=None, size=[1100, None], upload_to='catalog_page/add_question/', verbose_name='Фото'),
        ),
    ]
